#!/bin/bash
yum install epel-release bash-completion vim ntp bzip2 net-tools mlocate -y
echo alias vi=vim >> /etc/bashrc
mkdir .ssh
touch .ssh/authorized_keys
#cat id_rsa.pub >> .ssh/authorized_keys
sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config
systemctl stop NetworkManager
systemctl disable NetworkManager
yum remove NetworkManager
#systemctl stop firewalld.service
#systemctl disable firewalld.service
yum update -y
firewall-cmd --add-service=ntp --permanent
firewall-cmd --reload
systemctl start ntpd
systemctl enable ntpd
reboot
